version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 55046:1972
      - 55047:52773
      - 55048:53773
    volumes:
      - ./:/irisrun/repo